### ISSUE TITLE
Error Starting application

### ISSUE THREAD

**Issue by rrosson** [jyruzicka/kanban#5]
Your Rack app raised an exception when Pow tried to run it.

NoMethodError: undefined method `join' for #<String:0x007fac535a1c50>
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:37:in`rescue in call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.3.6/lib/sinatra/showexceptions.rb:21:in `call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:124:in`call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `block in call'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1499:in`synchronize'
/Library/Ruby/Gems/2.0.0/gems/sinatra-1.3.6/lib/sinatra/base.rb:1417:in `call'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:155:in`handle'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:109:in `rescue in block (2 levels) in start'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:106:in`block (2 levels) in start'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `each'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in`block in start'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in`start'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
~/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in`<main>'

**Comment by jyruzicka** [comment]
Unsure as to the cause of this...

Have you tried updating `sinatra`? By my count I'm currently at V 1.4.5

**Comment by rrosson** [comment]
That worked but the page has lost its columns and the cards go the width of the web browser.

—
Ron Rosson
ron@oneinsane.org mailto:ron@oneinsane.org

**Comment by jyruzicka** [comment]
Sorry for the incredible delay in responding - lots of plates spinning right now.

What does your `config.yaml` file look like?
