### ISSUE TITLE
css is not used

### ISSUE THREAD

**Issue by granin** [jyruzicka/kanban#6]
App looks like this: 
https://www.dropbox.com/s/gbbc60l4vh7c3h6/Screenshot%202015-04-12%2019.48.29.png?dl=0

**Comment by jyruzicka** [comment]
What do you see if you go to `/styles.css` in your app?

**Comment by granin** [comment]
```
Error starting application
Your Rack app raised an exception when Pow tried to run it.
ArgumentError: invalid byte sequence in US-ASCII
~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/utils.rb:241:in `gsub'
~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/utils.rb:241:in `escape_html'
~/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:103:in `h'
(erb):177:in `block in pretty'
(erb):155:in `each'
Show 20 more lines...
```

![Screenshot of what is on styles.css](https://dl.dropboxusercontent.com/u/347817/j/1.png)

**Comment by granin** [comment]
I don’t see this file at all, I suppose it is not generated, updated Ruby and Sinatra to latest stable version, still same problem, here is how app folder looks:

**Comment by jyruzicka** [comment]
Hi @granin - sorry for the incredible delay in dealing with this. Life has been somewhat busy of late.

My only guess for what's happening is that somewhere in the process you're using UTF-8, and ruby/sinatra/something is expecting ASCII. Ideally, the app should just deal with UTF-8. I'm planning on chucking some UTF-8 at my copy of kanban and seeing what it does - hopefully in the near future, but no guarantees I'm afraid.

**Comment by granin** [comment]
thank you, so the only way for me for now would be to start from scratch to make sure there are no non-ASCII  characters and use only ASCII?

**Comment by jyruzicka** [comment]
Had a look at the stack trace. I'm not quite sure where it's coming from, but I can have a go at tracing it back through the app.

When you get your error message, can you click "Show 20 more lines" and post the whole backtrace?
